# Use the official lightweight Python 3.11-slim image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY . /app

# Command to run the application when the container starts
CMD ["python3", "app.py"]

